name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: reuters-graphics/action-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      node_versions: '[20,22]'
      build_script: 'build:lib'
